[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# "suggest-hanja" 함수의 제한 시간을 20초로 늘립니다.
[functions."suggest-hanja"]
  timeout = 20

# 이 플러그인이 package.json의 부품을 강제로 설치합니다.
[[plugins]]
  package = "@netlify/plugin-functions-install-core"
