[build]
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[functions."suggest-hanja"]
  timeout = 20

[[plugins]]
  package = "@netlify/plugin-functions-install-core"
